substitutions:
  # Wi-Fi Substitutions
  api_key: !secret api_key
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password

# Enable Home Assistant API
api:
  #encryption:
    #key: "${api_key}"

sensor:
  - platform: wifi_signal
    name: "RSSI"
    id: sensor_rssi
    update_interval: 60s
    entity_category: "diagnostic"

# Enable OTA
ota:
  safe_mode: true
  password: "${ota_password}"

# Enable WiFi and AP for captive portal
wifi:
  fast_connect: false
  power_save_mode: none
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"
  #use_address: "${device_ip}"

  # Enable fallback hotspot (captive portal) in case wi-fi connection fails
  ap:
    ssid: "${device_name}"
    password: "${wifi_password}"

captive_portal:

web_server:
  port: 80