substitutions:
  # User-required substitutions
  device_location_code: "office"
  device_location_name: "Office"
  device_type_code: "light-switch"
  device_type_name: "light switch"
  device_number: "2"
  #device_ip: "0.0.0.0"

  # Project Substitutions (not intended for user substitution)
  device_model: "Switchman M5 (1-Gang)"
  device_make: "Sonoff"
  package_version: "0.0.1"
  package_url: "github://bitosome/esphome/sonoff-m5-1-gang.yaml@main"

  # Relay Configurations
  relay_a_gpio: GPIO23

  # Button Configurations
  button_a_gpio: GPIO00

  # Indicator LED
  led_indicator_gpio: GPIO19

# Allow importing this package
dashboard_import:
  package_import_url: ${package_url}
  import_full_config: false

# Import packages
packages:
  standard_package:
    url: https://github.com/bitosome/esphome/
    ref: main
    refresh: 0d
    files:
      - standard/project.yaml
      - standard/diagnostics.yaml
      - standard/wifi.yaml
      - standard/internaltemp.yaml
  sonoffm5_package:
    url: https://github.com/bitosome/esphome/
    ref: main
    refresh: 0d
    files:
      - sonoff-m5/board.yaml 
      - sonoff-m5/timings.yaml
      - sonoff-m5/status-led.yaml
      - sonoff-m5/backlight.yaml
      - sonoff-m5/indicator-led.yaml
      - sonoff-m5/mode-button-a.yaml
      - sonoff-m5/relay-a.yaml
      - sonoff-m5/button-a.yaml

switch:
    
  # Modify behavior of imported Relay A
  - id: !extend relay_a
    on_turn_on:
    - switch.turn_on: led_indicator
    on_turn_off:
    - switch.turn_off: led_indicator

binary_sensor:
  # Button A
  - id: !extend button_a
    pin:
      ignore_strapping_warning: true
    on_press:
      # Latching
      - if:
          condition:
            - lambda: 'return id(mode_a).active_index() == 0;'
          then:
            - switch.toggle: relay_a
      # Momentary
      - if:
          condition:
            - lambda: 'return id(mode_a).active_index() == 1;'
          then:
            - switch.turn_on: relay_a
      # Pulse
      - if:
          condition:
            - lambda: 'return id(mode_a).active_index() == 2;'
          then:
            - switch.turn_on: relay_a
            - delay: ${timing_pulse}
            - switch.turn_off: relay_a
      # Decoupled
      - if:
          condition:
            - lambda: 'return id(mode_a).active_index() == 3;'
          then:
            - switch.turn_on: led_indicator

    on_release:
      # Momentary
      - if:
          condition:
            - lambda: 'return id(mode_a).active_index() == 1;'
          then:
            - switch.turn_off: relay_a
      # Decoupled
      - if:
          condition:
            - lambda: 'return id(mode_a).active_index() == 3;'
          then:
            - switch.turn_off: led_indicator
